name: Webtool CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]  # Define the Node.js versions to test against

    steps:
    - uses: actions/checkout@v3  # Check out the code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install  # Install dependencies

    - run: npm run lint  # Run linting to check for syntax or formatting issues

    - run: npm run build  # Build the Next.js application
